### ISSUE TITLE
pipeline question

### ISSUE THREAD

**Issue by Gynjn** [Chrixtar/latent-gaussian-rasterization#1]
First thanks for sharing your great work.

BTW, I'm curious about the meaning of 

> stop gradient through features to all structural Gaussian parameters

Could you explain more details and why use stop gradient?

Thanks!

**Comment by Chrixtar** [comment]
Hi Gynjn,

thank you for your interest in our work.
There are two branches for the rasterizer with the difference being that for ```alpha_grad_through_features``` there is also the gradient d_features/d_alpha implemented. That means that alpha and therefore all structural parameters of the Gaussians used to compute alpha during rasterization are also optimized for the splatted feature maps and the respecitve loss terms after decoding it.

However, since the meaning of the latent features depends on the jointly optimized decoder network in latentSplat, we find that such a gradient does not give a useful signal for the geometry optimization but leads to more unstable training.
Therefore, we drop this gradient during rasterization as implemented in the ```main``` branch.

I hope this helps.

Best
Chris
